image:
  name: <a docker registry with docker image built from this branch>
  tag: main-blb

port: 8080

resources:
  limits:
    memory: 75Mi
  requests:
    cpu: 75m
    memory: 50Mi

scaphandre:
  command: prometheus
  args: {}
  extraArgs:
    containers:
    address: 0.0.0.0
#  rustBacktrace: '1'

# Run as root user to get proper permissions
userID: 0
groupID: 0
